#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
VAULT_DIR="${OBSIDIAN_VAULT_DIR:-/home/admlibrary/knowledge/kazutb-library-vault}"
TODAY="$(date +%F)"
TODAY_FILE="$VAULT_DIR/09-daily-notes/${TODAY}.md"
HANDOFF_FILE="$VAULT_DIR/11-handoffs/latest-agent-handoff.md"
TASK_LOG_DIR="$VAULT_DIR/11-handoffs/task-log"
BRANCH="$(git -C "$ROOT_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"

mkdir -p "$VAULT_DIR/09-daily-notes" "$VAULT_DIR/11-handoffs" "$TASK_LOG_DIR" "$VAULT_DIR/12-reference"

MAP_STATUS="skipped (generator not found)"
if [[ -f "$ROOT_DIR/scripts/dev/generate-obsidian-code-maps.sh" ]]; then
  if bash "$ROOT_DIR/scripts/dev/generate-obsidian-code-maps.sh" >/dev/null 2>&1; then
    MAP_STATUS="refreshed from current repo paths"
  else
    MAP_STATUS="refresh failed (run generator manually for details)"
  fi
fi

if [[ ! -f "$TODAY_FILE" ]]; then
  cat > "$TODAY_FILE" <<EOF
# ${TODAY} — session notes

## Session start
- branch: ${BRANCH}
- repo: $(basename "$ROOT_DIR")
- startup files reviewed:
  - AGENT_START_HERE.md
  - project-context/00-canonical-platform-truth.md
  - project-context/01-runtime-stack-and-entrypoints.md
  - project-context/02-domain-boundaries-and-integrations.md
  - project-context/03-operational-realities-and-data-truth.md
  - project-context/04-active-delivery-focus-and-risks.md
  - vault read-first / root-context / current-next-step / workstreams / latest handoff

## What I intend to change
- 

## Notes collected during the session
- 

## Verification
- 

## Risks / regressions
- 

## Next step
- 
EOF
fi

cat <<EOF
Deterministic startup path for this session:
1. $ROOT_DIR/AGENT_START_HERE.md
2. $ROOT_DIR/project-context/00-canonical-platform-truth.md
3. $ROOT_DIR/project-context/01-runtime-stack-and-entrypoints.md
4. $ROOT_DIR/project-context/02-domain-boundaries-and-integrations.md
5. $ROOT_DIR/project-context/03-operational-realities-and-data-truth.md
6. $ROOT_DIR/project-context/04-active-delivery-focus-and-risks.md
7. $ROOT_DIR/docs/developer/OBSIDIAN_VAULT_ARCHITECTURE.md
8. $ROOT_DIR/docs/developer/AI_SDLC_WORKFLOW.md
9. $VAULT_DIR/00-index/read this first before any new agent session.md
10. $VAULT_DIR/00-index/root context graph - kazutb smart library.md
11. $VAULT_DIR/00-index/current-next-step.md
12. $VAULT_DIR/08-workstreams/current-workstreams.md
13. $VAULT_DIR/07-bugs-and-incidents/active problem register - runtime, data, and integration.md
14. $HANDOFF_FILE
15. $TODAY_FILE

Default delivery mode:
- write one line in docs/sdlc/current/draft.md
- run /autopilot (or /remember for context-only updates)

Generated code maps:
- $MAP_STATUS
- $VAULT_DIR/00-index/code map index - autogenerated from repo paths.md

Session note and task logs:
- daily note: $TODAY_FILE
- latest handoff: $HANDOFF_FILE
- task log directory: $TASK_LOG_DIR
EOF
