#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
VAULT_DIR="${VAULT_DIR:-/home/admlibrary/knowledge/kazutb-library-vault}"
INDEX_DIR="$VAULT_DIR/00-index"
INDEX_FILE="$INDEX_DIR/repo-context-index.md"

mkdir -p "$INDEX_DIR"

cat > "$INDEX_FILE" <<EOF
# Repo Context Index (Mirror)

> Source of truth remains the repository.
> This note is a mirror index for navigation only.

## Canonical startup files
- [[09-reference-mirrors/repo-context/AGENT_START_HERE.md]]
- [[09-reference-mirrors/repo-context/project-context/00-project-truth.md]]
- [[09-reference-mirrors/repo-context/project-context/01-current-stage.md]]
- [[09-reference-mirrors/repo-context/project-context/06-current-focus.md]]
- [[09-reference-mirrors/repo-context/project-context/05-agent-working-rules.md]]

## Planning/deep context
- [[09-reference-mirrors/repo-context/project-context/02-active-roadmap.md]]
- [[09-reference-mirrors/repo-context/project-context/03-api-contracts.md]]
- [[09-reference-mirrors/repo-context/project-context/04-known-risks.md]]
- [[09-reference-mirrors/repo-context/project-context/98-product-master-context.md]]

## Normalization and workflow
- [[09-reference-mirrors/repo-context/docs/developer/REPO_NORMALIZATION_PLAN.md]]
- [[09-reference-mirrors/repo-context/docs/developer/FULL_SYSTEM_NORMALIZATION_PLAN.md]]
- [[09-reference-mirrors/repo-context/docs/developer/OBSIDIAN_VAULT_ARCHITECTURE.md]]
- [[09-reference-mirrors/repo-context/docs/developer/AGENT_AUTOMATION_WORKFLOW.md]]

## Sync metadata
- Generated by: \`scripts/dev/sync-vault-index.sh\`
- Repo path: \`$REPO_DIR\`
- UTC timestamp: \`$(date -u +"%Y-%m-%dT%H:%M:%SZ")\`
EOF

echo "Vault index updated: $INDEX_FILE"
